[DHL]
UserId    = "uuid"
ApiKey    = "uuid"
AccountId = "0700000"

[Lightspeed]
Frontend = "https://<subdomain>.webshopapp.com"
Cluster = "https://api.webshopapp.com/en/"
Key     = ""
Secret  = ""
ShopId = ""
ClusterId = ""

[CompanyInfo]
Name         = ""
Street       = ""
City         = ""
PostalCode   = ""
CountryCode  = ""
Number       = ""
Addition     = ""
Email        = ""
PhoneNumber  = ""
PersonalNote = "Your order is on it's way!"

[Options]
DryRun      = false
Port        = 3000
Environment = "development"
Debug       = true
PollingInterval = 5 
