env: local

dryRun: true
debug: true

gateway:
  className: envoy
  issuerName: letsencrypt-staging

configSecret:
  name: config
  key: config.toml

webhook:
  minReplicas: 1
  maxReplicas: 3
  hostnames:
    - adapter.cluster.localhost
  probe:
    enabled: false

pollStatus:
  schedule: "*/5 * * * *" # every 5 minutes
  jobHistoryLimit: 3

markStale:
  schedule: "*/5 * * * *" # every 5 minutes
  jobHistoryLimit: 3

clusterDB:
  replicas: 1
  storageSize: 1Gi

metrics:
  enabled: false

